### ISSUE TITLE
Android build started failing recently with errors in RNConvivaTrackerModule.java

### ISSUE THREAD

**Issue by kot331107** [Conviva/conviva-react-native-appanalytics#1]
Hello and first of all thank you for this lib!
Recently our android builds started to fail in RNConvivaTrackerModule.java having issues with the prop `event.customContexts` in a few places.
We found that you have a dependency in build.gradle declared as follows.
`implementation “com.conviva.sdk:conviva-android-tracker:+`
It looks like conviva-android-tracker is published with a new version which includes some breaking changes. 
Suggestion: 
To replace the current declaration with pinned specific version, e.g. 0.8.2 works fine.
`implementation “com.conviva.sdk:conviva-android-tracker:0.8.2`
Also I wanted to mention that Android Studio highlights `+` usage in dependencies with the error `avoid using + in version numbers can lead to unpredictable and unrepeatable builds`.
Thank you!

**Comment by SarathRamachandra** [comment]
@kot331107 Thanks for reaching out for Conviva and sorry for the delay from our side.
The issue mentioned is resolved in the following release version:

[v0.9.2](https://github.com/Conviva/conviva-android-appanalytics/releases/tag/v0.9.2)
0.9.2 (20/MAY/2024)
Fixes the build issue of the [react native sensor](https://github.com/Conviva/conviva-react-native-appanalytics) introduced in 0.9.0 version of sensor

We will update you on the dependency of `implementation “com.conviva.sdk:conviva-android-tracker:+` after discussing with corresponding folks.
