### ISSUE TITLE
Task :convivainc_conviva-react-native-appanalytics:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by Gopal402402** [Conviva/conviva-react-native-appanalytics#2]
Hi,

"@convivainc/conviva-react-native-appanalytics": "^0.2.0" fails with Android setup(everything latest)

Error in console - Task :convivainc_conviva-react-native-appanalytics:compileDebugJavaWithJavac FAILED

Please let me know if you need more details.

**Comment by SarathRamachandra** [comment]
@Gopal402402 please give us some time, to look into this issue and we will update you soon on the resolution.

**Comment by SarathRamachandra** [comment]
@Gopal402402 Can you please try building again, we have resolved the issue from our side. The tracker version should show andr-0.9.8.1 rn-0.2.0 once you are able to build it. Once you confirm we can close the issue.

**Comment by Gopal402402** [comment]
@SarathRamachandra Thank you for the fix. It is working fine now.
This issue can be closed.
